version: 2.1

orbs:
  kitchen: sous-chefs/kitchen@2

workflows:
  kitchen:
    jobs:
      - kitchen/danger:
          name: danger
          context: Danger
      - kitchen/lint:
          name: lint
